/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MasterRouteImport } from './routes/master'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRoleRouteImport } from './routes/dashboard.$role'
import { Route as DSlugRouteImport } from './routes/d.$slug'

const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoleRoute = DashboardRoleRouteImport.update({
  id: '/dashboard/$role',
  path: '/dashboard/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const DSlugRoute = DSlugRouteImport.update({
  id: '/d/$slug',
  path: '/d/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/d/$slug': typeof DSlugRoute
  '/dashboard/$role': typeof DashboardRoleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/d/$slug': typeof DSlugRoute
  '/dashboard/$role': typeof DashboardRoleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/d/$slug': typeof DSlugRoute
  '/dashboard/$role': typeof DashboardRoleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/master' | '/d/$slug' | '/dashboard/$role'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/master' | '/d/$slug' | '/dashboard/$role'
  id: '__root__' | '/' | '/login' | '/master' | '/d/$slug' | '/dashboard/$role'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MasterRoute: typeof MasterRoute
  DSlugRoute: typeof DSlugRoute
  DashboardRoleRoute: typeof DashboardRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$role': {
      id: '/dashboard/$role'
      path: '/dashboard/$role'
      fullPath: '/dashboard/$role'
      preLoaderRoute: typeof DashboardRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$slug': {
      id: '/d/$slug'
      path: '/d/$slug'
      fullPath: '/d/$slug'
      preLoaderRoute: typeof DSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MasterRoute: MasterRoute,
  DSlugRoute: DSlugRoute,
  DashboardRoleRoute: DashboardRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
